version: "0.1-beta"

listener:
  address: 0.0.0.0
  port: 10000
  message_format: huggingface
  connect_timeout: 500ms

endpoints:
  api_server:
    endpoint: api_server
    connect_timeout: 500ms
    timeout: 10000ms

llm_providers:
  - name: open-ai-gpt-4
    access_key: $OPEN_AI_API_KEY
    model: gpt-4
    default: true

overrides:
  # confidence threshold for prompt target intent matching
  prompt_target_intent_matching_threshold: 0.6

system_prompt: |
  You are a helpful assistant.

prompt_targets:

  - name: weather_forecast
    type: function_resolver
    description: This function provides realtime weather forecast information for a given city.
    parameters:
      - name: city
        required: true
        description: The city for which the weather forecast is requested.
      - name: days
        description: The number of days for which the weather forecast is requested.
      - name: units
        description: The units in which the weather forecast is requested.
    endpoint:
      name: api_server
      path: /weather
    system_prompt: |
      You are a helpful weather forecaster. Use weater data that is provided to you. Please following following guidelines when responding to user queries:
      - Use farenheight for temperature
      - Use miles per hour for wind speed

  - name: insurance_claim_details
    type: function_resolver
    description: This function resolver provides insurance claim details for a given policy number.
    parameters:
      - name: policy_number
        required: true
        description: The policy number for which the insurance claim details are requested.
        type: string
      - name: include_expired
        description: whether to include expired insurance claims in the response.
        type: bool
        required: true
    endpoint:
      name: api_server
      path: /insurance_claim_details
    system_prompt: |
      You are a helpful insurance claim details provider. Use insurance claim data that is provided to you. Please following following guidelines when responding to user queries:
      - Use policy number to retrieve insurance claim details
