default_prompt_endpoint: "127.0.0.1"
load_balancing: "round_robin"
timeout_ms: 5000

overrides:
  # confidence threshold for prompt target intent matching
  prompt_target_intent_matching_threshold: 0.7

# should not be here
embedding_provider:
  name: "bge-large-en-v1.5"
  model: "BAAI/bge-large-en-v1.5"

llm_providers:

  - name: open-ai-gpt-4
    api_key: $OPEN_AI_API_KEY
    model: gpt-4
    default: true

prompt_targets:

  - type: function_resolver
    name: interface_down_pkt_drop
    description: |
      This tool checks for packet drops due to interface down events by correlating timestamps between interfacestats and ts_flow. It allows filtering the results by timeframes, interface name, region, and packet error thresholds.
    parameters:
      - name: from_time
        description: An optional natural language timeframe (e.g., "past 7 days", "since a month") to define the time range for packet drop analysis.
        required: false
        type: string
      - name: ifname
        description: An optional interface name filter to apply.
        required: false
        type: string
      - name: region
        description: An optional region filter to apply (from the device table).
        required: false
        type: string
      - name: min_in_errors
        description: Minimum number of in_errors to filter results.
        required: false
        type: integer
      - name: max_in_errors
        description: Maximum number of in_errors to filter results.
        required: false
        type: integer
      - name: min_out_errors
        description: Minimum number of out_errors to filter results.
        required: false
        type: integer
      - name: max_out_errors
        description: Maximum number of out_errors to filter results.
        required: false
        type: integer
      - name: min_in_discards
        description: Minimum number of in_discards to filter results.
        required: false
        type: integer
      - name: max_in_discards
        description: Maximum number of in_discards to filter results.
        required: false
        type: integer
      - name: min_out_discards
        description: Minimum number of out_discards to filter results.
        required: false
        type: integer
      - name: max_out_discards
        description: Maximum number of out_discards to filter results.
        required: false
        type: integer
    endpoint:
      cluster: databasehost
      path: /interface_down_pkt_drop
    system_prompt: |
      You are responsible for correlating packet drops with interface down events by analyzing packet errors in the interfacestats table and flows in the ts_flow table, based on optional filters like timeframe, interface name, region, and packet error thresholds.
