version: "0.1-beta"
listener:
  address: 127.0.0.1
  port: 8080 #If you configure port 443, you'll need to update the listener with tls_certificates
  messages: hugging-face

system_prompts:
- name: insurance_agent
  content: You are an insurance assistant that just offers guidance related to car, boat, rental and home insurnace only.

llm_providers:
  - name: "OpenAI"
    access_key: $OPEN_AI_KEY
    model: gpt-4o
    default: true

prompt_endpoints:
  - "http://127.0.0.2:8000"
  
prompt_targets:
  - name: policy_qa
    path: /policy/qa
    description: "This method handles Q/A related to general issues in insurance. It forwards the conversation to the OpenAI client via a local proxy and returns the response."
    default: true

  - name: get_policy_coverage
    path: /policy/coverage
    description: Retrieve the coverage details for a given policy type (car, boat, house, motorcycle).
    parameters:
    - name: policy_type
      type: str
      description: The 
      default_value: 'car'
      required: true

  - name: initiate_policy
    path: /policy/initiate
    description: Initiate policy coverage for a car, boat, house, or motorcycle.
    parameters:
    - name: policy_type
      type: str
      description: Field definition from Pydantic model. Requires fixes PolicyRequest
      required: true
    - name: details
      type: Unknown
      description: Field definition from Pydantic model. Requires fixes PolicyRequest
      required: false

  - name: update_claim
    path: /policy/claim
    description: Update the status or details of a claim.
    parameters:
    - name: claim_id
      type: int
      description: Field definition from Pydantic model. Requires fixes ClaimUpdate
      required: true
    - name: update
      type: str
      description: Field definition from Pydantic model. Requires fixes ClaimUpdate
      required: false

  - name: update_deductible
    path: /policy/deductible
    description: Update the deductible amount for a specific policy.
    parameters:
    - name: policy_id
      type: int
      description: Field definition from Pydantic model. Requires fixes DeductibleUpdate
      required: true
    - name: new_deductible
      type: float
      description: Field definition from Pydantic model. Requires fixes DeductibleUpdate
      required: false

