services:
  envoy:
    image: envoyproxy/envoy:v1.30-latest
    hostname: envoy
    ports:
      - "10000:10000"
      - "19901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./target/wasm32-wasi/release:/etc/envoy/proxy-wasm-plugins
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
    networks:
      - envoymesh

networks:
  envoymesh: {}
