version: "0.1-beta"

listener:
  address: 0.0.0.0
  port: 10000
  message_format: huggingface
  connect_timeout: 0.005s

endpoints:
  api_server:
    endpoint: api_server:80
    connect_timeout: 0.005s

llm_providers:
  - name: open-ai-gpt-4
    access_key: $OPEN_AI_API_KEY
    model: gpt-4
    default: true

overrides:
  # confidence threshold for prompt target intent matching
  prompt_target_intent_matching_threshold: 0.7

system_prompt: |
  You are a helpful assistant.

prompt_targets:

  - name: top_employees
    description: |
      Allows you to find the top employees in different groups, such as departments, locations, or position. You can rank the employees by different criteria, like salary, yoe, or rating. Returns the best-ranked employees for each group, helping you identify top n in the list.
    parameters:
      - name: grouping
        description: |
          Select how you'd like to group the employees. For example, you can group them by department, location, or their position. The function will provide the top-ranked employees within each group you choose.
        required: true
        type: str
        enum: [department, location, position]
      - name: ranking_criteria
        required: true
        type: str
        description: |
          Choose how you'd like to rank the employees. You can rank them by their salary, their years of experience, or their rating. The function will sort the employees based on this ranking and return the best ones from each group.
        enum: [salary, years_of_experience, performance_score]
      - name: top_n
        required: false
        type: int
        default: 3
        description: |
          Enter how many of the top employees you want to see in each group. For example, if you enter 3, the function will show you the top 3 employees for each group you selected.
    endpoint:
      name: api_server
      path: /top_employees
    system_prompt: |
      You are responsible for retrieving the top N employees per group ranked by a constraint.

  - name: aggregate_stats
    description: |
       Calculate summary statistics for groups of employees. You can group employees by categories like department or location and then compute totals, averages, or other statistics for specific attributes such as salary or years of experience.
    parameters:
      - name: grouping
        description: |
          Choose how you'd like to organize the employees. For example, you can group them by department, location, or position. The function will calculate the summary statistics for each group.
        required: true
        type: str
        enum: [department, location, position]
      - name: aggregate_criteria
        description: |
          Select the specific attribute you'd like to analyze. This could be something like salary, years of experience, or rating. The function will calculate the statistic you request for this attribute.
        required: true
        type: str
        enum: [salary, years_of_experience, performance_score]
      - name: aggregate_type
        description: |
          Choose the type of statistic you'd like to calculate for the selected attribute. For example, you can calculate the sum, average, minimum, or maximum value for each group.
        required: true
        type: str
        enum: [SUM, AVG, MIN, MAX]
    endpoint:
      name: api_server
      path: /aggregate_stats
    system_prompt: |
      You help calculate summary statistics for groups of employees. First, organize the employees by the specified grouping (e.g., department, location, or position). Then, compute the requested statistic (e.g., total, average, minimum, or maximum) for a specific attribute like salary, experience, or rating.

  # Top Employees by Performance, Projects, and Timeframe
  - name: employees_projects
    description: |
      Fetch employees with the highest performance scores, considering their project participation and years of experience. You can filter by minimum performance score, years of experience, and department. Optionally, you can also filter by recent project participation within the last Y months.
    parameters:
      - name: min_years_experience
        description: Minimum years of experience to filter employees.
        required: true
        type: int
      - name: department
        description: Department to filter employees by.
        required: true
        type: str
      - name: min_performance_score
        description: Minimum performance score to filter employees.
        required: false
        type: float
        default: 4.0
      - name: min_project_count
        description: Minimum number of projects employees participated in (optional).
        required: false
        type: int
        default: 3
      - name: months_range
        description: Timeframe (in months) for filtering recent projects (optional).
        required: false
        type: int
    endpoint:
      name: api_server
      path: /employees_projects
    system_prompt: |
      You are responsible for retrieving the top N employees ranked by performance and project participation. Use filters for experience and optional project criteria.

  # Employees with Salary Growth Since Last Promotion
  - name: salary_growth
    description: |
      Fetch employees with the highest salary growth since their last promotion, grouped by department. You can filter by a minimum salary increase percentage and department.
    parameters:
      - name: min_salary_increase_percentage
        description: Minimum percentage increase in salary since the last promotion.
        required: true
        type: float
      - name: department
        description: Department to filter employees by (optional).
        required: false
        type: str
        default: "Sales"
    endpoint:
      name: api_server
      path: /salary_growth
    system_prompt: |
      You are responsible for retrieving employees with the highest salary growth since their last promotion. Filter by minimum salary increase percentage and department.

  # Employees with Promotions and Salary Increases by Year
  - name: promotions_increases
    description: |
      Fetch employees who were promoted and received a salary increase in a specific year, grouped by department. You can optionally filter by minimum percentage salary increase and department.
    parameters:
      - name: year
        description: The year in which the promotion and salary increase occurred.
        required: true
        type: int
      - name: min_salary_increase_percentage
        description: Minimum percentage salary increase to filter employees.
        required: false
        type: float
        default: 10.0
      - name: department
        description: Department to filter by (optional).
        required: false
        type: str
        default: "Engineering"
    endpoint:
      name: api_server
      path: /promotions_increases
    system_prompt: |
      You are responsible for fetching employees who were promoted and received a salary increase in a specific year. Apply filters for salary increase percentage and department.

  # Employees by Certification and Years of Experience
  - name: certifications_experience
    description: |
      Fetch employees who have all the required certifications and meet the minimum years of experience. You can filter by department and provide a list of certifications to match.
    parameters:
      - name: certifications
        description: List of required certifications.
        required: true
        type: list
      - name: min_years_experience
        description: Minimum years of experience.
        required: true
        type: int
      - name: department
        description: Department to filter employees by (optional).
        required: false
        type: str
    endpoint:
      name: api_server
      path: /certifications_experience
    system_prompt: |
      You are responsible for fetching employees who have the required certifications and meet the minimum years of experience. Optionally, filter by department.

ratelimits:
  - provider: gpt-3.5-turbo
    selector:
      key: selector-key
      value: selector-value
    limit:
      tokens: 1
      unit: minute
