name: Checks

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.OPEN_MESSAGE_FORMAT_GITHUB_TOKEN }}
      - name: Setup | Rust
        run: rustup toolchain install stable --profile minimal
      - name: Run Clippy
        run: cd envoyfilter && cargo clippy --all-targets --all-features -- -Dwarnings

  format:
    name: Rustfmt
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup | Rust
        run: rustup toolchain install stable --profile minimal
      - name: Run Rustfmt
        run: cd envoyfilter && cargo fmt --all -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup | Rust
        run: rustup toolchain install stable --profile minimal
      - name: Run Tests
        # --lib is to only test the library, since when integration tests are made,
        # they will be in a seperate tests directory
        run: cd envoyfilter && cargo test --lib
